One xsd file creates only one _xsd.lua file which contains all the mappings for rockspec file

diff --git a/bin/gxsd b/bin/gxsd
--- a/bin/gxsd
+++ b/bin/gxsd
@@ -1,9 +1,19 @@
 #/usr/bin/sh
 
 output_directory=$2
-if [ $# -eq 0 ]
+if [ $# -lt 1 ]
 then
 	echo "Usage: gxsd [ all | <xsd_file_name> ] <output_directory>"
+	exit 1
+fi
+if [ -f $HOME/.luarocks/share/lua/5.3/generate_schema.lua ]
+then
+	LUA_FILE="$HOME/.luarocks/share/lua/5.3/generate_schema.lua"
+elif [ -f /usr/local/share/lua/5.3/generate_schema.lua ]
+then
+	LUA_FILE="/usr/local/share/lua/5.3/generate_schema.lua"
+else
+	echo "File generate_schema.lua not found"
 	exit 1
 fi
 
@@ -13,17 +23,29 @@ then
 	then
 		mkdir -p $output_directory
 		cd $output_directory
+		for file in `ls -1 xsd_for_test/*.xsd`
+		do
+			echo "Generating "$file
+			echo "--------------"
+			lua $LUA_FILE ../$file $output_directory
+			if [ $? -ne 0 ]
+			then
+				exit 1;
+			fi
+		done
+		cd ..
+	else
+		for file in `ls -1 xsd_for_test/*.xsd`
+		do
+			echo "Generating "$file
+			echo "--------------"
+			lua $LUA_FILE $file
+			if [ $? -ne 0 ]
+			then
+				exit 1;
+			fi
+		done
 	fi
-	for file in `ls -1 xsd_for_test/*.xsd`
-	do
-		echo "Generating "$file
-		echo "--------------"
-		lua $HOME/.luarocks/share/lua/5.3/generate_schema.lua $file $output_directory
-		if [ $? -ne 0 ]
-		then
-			exit 1;
-		fi
-	done
 else
 	file=$1
 	echo "Generating "$file
@@ -32,11 +54,17 @@ else
 	then
 		mkdir -p $output_directory
 		cd $output_directory
+		lua $LUA_FILE ../$file
+		if [ $? -ne 0 ]
+		then
+			exit 1;
+		fi
+		cd ..
+	else
+		lua $LUA_FILE $file
+		if [ $? -ne 0 ]
+		then
+			exit 1;
+		fi
 	fi
-	lua $HOME/.luarocks/share/lua/5.3/generate_schema.lua ../$file
-	if [ $? -ne 0 ]
-	then
-		exit 1;
-	fi
-	
 fi
